[profile.release]
debug = true

[workspace]

members = [
    "board-perft",
    "board",
    "core",
    "engine-app",
    "engine-core",
    "engine-piece-square-table-generator",
    "lichess-api",
    "lichess-bot",
    "pgn",
    "pgn-test",
    "uci",
]
