[profile.release]
debug = true

[workspace]

members = [
    "board_perft",
    "board",
    "core",
    "engine_app",
    "engine_core",
    "engine_piece_square_table_generator",
    "lichess_api",
    "lichess_bot",
    "pgn",
    "pgn_test",
    "uci",
]
