[profile.release]
codegen-units = 1
lto = "fat"

[workspace]
resolver = "3"
members = [
    "board_perft",
    "board",
    "core",
    "engine_app",
    "engine_core",
    "engine_piece_square_table_generator",
    "lichess_api",
    "lichess_bot",
    "pgn",
    "pgn_test",
    "uci",
]
